on: push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: mkdir build
      - run: dart compile exe bin/glue_lang.dart -v -o "build/glue.exe"
      - uses: actions/upload-artifact@v1
        with:
          name: WindowsBuild
          path: build
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: mkdir build
      - run: dart compile exe bin/glue_lang.dart -v -o "build/glue"
      - uses: actions/upload-artifact@v1
        with:
          name: LinuxBuild
          path: build
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: mkdir build
      - run: dart compile exe bin/glue_lang.dart -v -o "build/glue"
      - uses: actions/upload-artifact@v1
        with:
          name: MacOSBuild
          path: build
